### ISSUE TITLE
"Use in reply the same format (html or text) of the original mail" does not work

### ISSUE THREAD

**Issue by sphh** [caligraf/ChangeQuote#35] opened 2022-09-25 09:39 UTC
In the configuration, I have the following set in `Format and actions`:
```
✓ Use in reply the same format (html or text) of the original mail
  Format for the mixed mails (content-type=alternative):
    Default
  ✓ Html
    Plain text
```

I would expect, the following behaviour:
1. Message is a plain text message → reply is in plain text
2. Message is a html message → reply is in html
3. Message has `content-type=alternative` → reply is in html

Unfortunately all 3 replies are in html, which is wrong for case 1.!

If I set
```
  ✓ Plain text
```
1. and 3. are in plain text and 2. in html. Here the format for 3. is wrong because IMHO it should be in html.

The header for case 3. is `Content-Type: multipart/alternative;`.

Thunderbird 91.11.0 (64-bit) on Linux Mint 20.3

**Comment by caligraf** [comment] 2023-10-25 19:13
This issue is a duplicate of #36

**Closed by caligraf** 2023-10-25 19:13 UTC
